#ifndef _ARDUINO_FOOBAR_H_
#define _ARDUINO_FOOBAR_H_

#include <esbmc.h>
/* Operational model header generated by generate_from_name.py */
/* Notes: Skeleton generated: please edit prototypes to match the real library API. */

void FooBar_init(void);
int FooBar_do(int param);

#endif